# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_auto_20170501_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image_url',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
