# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodie', '0002_auto_20170501_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=0)),
                ('warnings_allowed', models.IntegerField(default=3)),
                ('num_orders', models.IntegerField(default=0)),
                ('money_spent', models.IntegerField(default=0)),
                ('is_certified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='times_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
