# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, default=25000.0, max_digits=8)),
                ('rating', models.SmallIntegerField(default=0)),
                ('complaints', models.SmallIntegerField(default=0)),
                ('compliments', models.SmallIntegerField(default=0)),
                ('demotions_remaining', models.SmallIntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
