# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=70)),
                ('position', models.CharField(choices=[('CH', 'Chef'), ('DD', 'Delivery Driver'), ('MG', 'Manager')], default='DD', max_length=4)),
                ('salary', models.DecimalField(decimal_places=2, default=25000.0, max_digits=8)),
                ('rating', models.SmallIntegerField(default=0)),
                ('demotions_remaining', models.SmallIntegerField(default=2)),
                ('active', models.CharField(choices=[('AC', 'Active'), ('IN', 'Inactive')], default='AC', max_length=6)),
            ],
        ),
    ]
